site_name: 'FZU-RUN'
site_url: https://run.west2.online/
site_author: west2-online
site_description: '福州大学飞跃手册'
nav:
    - 首页: index.md
    - 关于: about.md
    - 贡献指南: contribute-guide.md
    - 转专业:
        - change-major/README.md
        - 计算机:
            - '[大一]25-给排水->软件工程': change-major/cs/251207-2.md
            - '[大一]25-数学->计算机类': change-major/cs/251206-8.md
            - '[大一]25-外国语->计算机类': change-major/cs/251206-7.md
            - '[大一]25-会计学->计算机类': change-major/cs/251206-6.md
            - '[大一]25-微电子科学与工程->软件工程': change-major/cs/251206-5.md
            - '[大一]25-数学->计算机类': change-major/cs/251206-4.md
            - '[大一]25-数学->软件工程': change-major/cs/251206-3.md
            - '[大一]25-应用物理->软件工程': change-major/cs/251206-2.md
            - '[大一]25-金融学->软件工程': change-major/cs/251206-1.md
            - '[大一]24-水利水电->计算机类': change-major/cs/250912-2.md
            - '[大一]25-数学类->数智实验班': change-major/cs/250912-1.md
            - '[大一]24-给排水->数智实验班': change-major/cs/250324-1.md
            - '[大一]24-数媒->计算机类': change-major/cs/241229-1.md
            - '[大二]23-数学->软件工程': change-major/cs/241122-1.md
            - '[大一]23-港航->计算机类': change-major/cs/231206-1.md
            - '[大一]23-建筑学->信息安全': change-major/cs/231204-1.md
            - '[大一]23-车辆工程->计算机类': change-major/cs/231203-3.md
            - '[大一]23-土木->软件工程': change-major/cs/231203-2.md
            # - '[大一]23-汉语言文学->软件工程': change-major/cs/231203-1.md
            - '[大一]23-机器人工程->计算机类': change-major/cs/231202-1.md
            - '[大一]22-光电信息->计算机类': change-major/cs/230828-1.md
            - '[大一]22-工业设计->大数据': change-major/cs/230808-1.md
            - '[大一]22-土木->软件工程': change-major/cs/230807-1.md
            - '[大二]22-高分子->软件工程': change-major/cs/230805-1.md
            - '[大一]22-土木->计算机类': change-major/cs/230810-2.md
            - '[大一]22-高分子->计算机类': change-major/cs/230810-1.md
            - '[大二]22-地矿->信息安全': change-major/cs/230319-1.md
            - '[大一]21-土木->计算机类': change-major/cs/230316-1.md
            - '[大一]21-环安->计算机类': change-major/cs/230316-6.md
            - '[大二]21-机械->计算机类': change-major/cs/230316-4.md
            - '[大二]21-生工->计算机类': change-major/cs/230316-3.md
            - '[大二]21-生工->软件工程': change-major/cs/230316-2.md
            - '[大一]21-土木->软件工程': change-major/cs/230316-5.md
            - '[大一]21-土木->软件工程': change-major/cs/230316-7.md
            - '[大二]21-材料->软件工程': change-major/cs/230316-8.md
        - 数学:
            - '[大一]23-土木->数学类': change-major/math/231208-1.md
            - '[大一]21-土木->数学类': change-major/math/230316-1.md
        - 电气:
            - '[大一]25-智能建造->自动化': change-major/electric/251208-1.md
            - '[大一]24-给排水->智能电网信息工程': change-major/electric/250928-1.md
            - '[大一]23-生工->智能电网信息工程': change-major/electric/231218-1.md
            - '[大二]22-机械->电气工程及其自动化': change-major/electric/230809-1.md
            - '[大二]21-土木->电气工程及其自动化': change-major/electric/230316-1.md
            - '[大一]21-环安->电气工程及其自动化': change-major/electric/230316-2.md
            - '[大一]21-化学->电气工程及其自动化': change-major/electric/230316-3.md
        - 物信:
            - '[大二]25-工程管理->集成电路设计与集成系统': change-major/physics/251209-3.md
            - '[大一]25-工程管理->数媒': change-major/physics/251209-2.md
            - '[大一]25-水利水电->量子信息科学': change-major/physics/251209-1.md
            - '[大一]25-外国语->数理综合班': change-major/physics/250912-1.md
            - '[大一]24-物流工程-微电子科学与工程': change-major/physics/250706-1.md
            - '[大一]24-数学类-电子科学与技术': change-major/physics/250706-2.md
            - '[大一]23-土木->电子信息类': change-major/physics/241111-1.md
            - '[大二]22-土木->电子科学与技术': change-major/physics/230809-1.md
            - '[大一]22-土木->电子信息类': change-major/physics/230810-1.md
            - '[大一]22-工业设计->电子信息类': change-major/physics/230810-2.md
            - '[大一]21-外国语->集成电路设计与集成系统': change-major/physics/230316-1.md
            - '[大一]21-化工->集成电路设计与集成系统': change-major/physics/230810-3.md
            - '[大二]22-物流工程->电信息科学与工程': change-major/physics/240213-1.md
            - '[大一]23-过程装备与控制工程->集成电路设计与集成系统 ': change-major/physics/240212-1.md
            - '[大二]23-物流工程->微电子科学与工程': change-major/physics/240211-1.md
            - '[大一]23-工程管理->电子信息类': change-major/physics/240211-2.md
            - '[大一]23-食品科学与工程->集成电路设计与集成系统': change-major/physics/240223-1.md
        - 机械:
            - '[大一]24-土木交通工程->车辆工程': change-major/mechanical-engineering/250624-1.md
        - 法学:
            - '[大一]22-英语->法学': change-major/law/230810-1.md
        - 外国语:
            - '[大一]21-计算机->英语': change-major/foreign/230316-1.md
        - 经管:
            - '[大一]25-土木->信息管理': change-major/economy/251208-1.md
            - '[大一]23-经济学->会计学': change-major/economy/231203-1.md
            - '[大一]23-工业设计->会计学': change-major/economy/231205-1.md
            - '[大一]22-外国语->数理金融实验班': change-major/economy/230316-1.md
            - '[大一]21-机械->数理金融实验班':  change-major/economy/230316-2.md
            - '[大一]21-土木->经济学': change-major/economy/230316-3.md
        - 化学:
            - '[大一]22-建筑->嘉锡化学拔尖班':  change-major/chemistry/230316-1.md
        - 汉语言文学:
            - '[大一]23-物流管理->汉语言文学': change-major/chinese-literature/240102-1.md
        - 备考资源:
            - 通用:
                - 官方文件: change-major/source/official-release.md
                - 转专业学生名单公示: change-major/source/major-student-list.md
            - 法学:
                - 2022法学转专业笔试题目: change-major/source/2022-law-write-exam.md
                - 2022法学转专业面试名单: change-major/source/2022-law-interview-list.md
                - 2023法学转专业笔试题目: change-major/source/2023-law-write-exam.md
            - 物信:
                - 2025物信转专业笔试题目: change-major/source/2025-physics-write-exam.md
                - 2022物信转专业笔试题目: change-major/source/2022-physics-write-exam.md
                - 2022物信转专业面试题目: change-major/source/2022-physics-interview-question.md
            - 电气:
                - 电气转专业物理复习资料: change-major/source/electric-review-data.md
            - 数学:
                - 2022数学转专业笔试题目: change-major/source/2022-math-write-exam.md
            - 经管:
                - 2022经管学院转专业英语考试B卷题目: change-major/source/2022-economy-english-B-write-exam.md
                - 2022经管学院转专业高等数学考试B卷题目: change-major/source/2022-economy-math-B-write-exam.md
            - 计算机:
                - 2025计算机大二机试题目: change-major/source/2025-cs-on-computer-exam.md
                - 2025计算机大一机试加赛题目: change-major/source/2025-cs-freshman-extra-on-computer-exam.md
                - 2025计算机大一机试题目: change-major/source/2025-cs-freshman-on-computer-exam.md
                - 2024计算机机试题目: change-major/source/2024-cs-on-computer-exam.md
                - 2023计算机机试题目: change-major/source/2023-cs-on-computer-exam.md
                - 2022计算机笔试题目: change-major/source/2022-cs-write-exam.md
                - 2022计算机机试题目: change-major/source/2022-cs-on-computer-exam.md
                - 2021计算机笔试题目: change-major/source/2021-cs-write-exam.md
                # - 计算机简答题整理: change-major/source/cs-intro.md
                - 20级计算机学院面试名单: change-major/source/2020-cs-interview-list.md
                - 21级计算机学院面试名单: change-major/source/2021-cs-interview-list.md
    - 研究生:
        - postgraduate/README.md
        - 福州大学:
            - '[考研] 2023-计算机与大数据学院': postgraduate/fzu/230320-1.md
            - '[考研] 2023-计算机与大数据学院': postgraduate/fzu/231214-1.md
            - '[考研] 2024-计算机与大数据学院': postgraduate/fzu/240629-1.md
        - 复旦大学:
            - "[考研] 2023-工程与应用技术研究院": postgraduate/fdu/231202-1.md
        - 厦门大学:
            - '[考研] 2023-信息学院': postgraduate/xmu/231230-1.md
            - '[保研] 2024-信息学院': postgraduate/xmu/231218-1.md
            - '[保研] 2024-信息学院': postgraduate/xmu/231204-1.md
            - '[保研] 2025-信息学院': postgraduate/xmu/241003-1.md
            - '[保研] 2025-信息学院': postgraduate/xmu/241017-1.md
            - '[保研] 2025-信息学院': postgraduate/xmu/250314-1.md
            - '[考研] 2025-人工智能研究院': postgraduate/xmu/250413-1.md
        - 清华大学:
            - '[保研] 2024-网络空间与网络科学研究院': postgraduate/thu/231208-1.md
        - 北京航空航天大学:
            - '[保研] 2024-计算机学院': postgraduate/buaa/240626-1.md
            - '[保研] 2023-计算机学院': postgraduate/buaa/231213-1.md
        - 湖南大学:
            - '[保研] 2024-艺术设计学院': postgraduate/hnu/231214-1.md
        - 同济大学:
            - '[保研] 2024-人工智能与自动化工程 （中德平台）': postgraduate/tongji/240312-1.md
        - 北京大学:
            - '[考研] 2024-软件与微电子学院': postgraduate/pku/240627-1.md
            - '[考研] 2025-软件与微电子学院': postgraduate/pku/250702-1.md
theme:
    logo: 'assets/logo.svg'
    icon:
        edit: material/pencil-box-multiple-outline
        view: material/file-eye-outline
        repo: fontawesome/brands/github
    name: material
    language: zh
    palette:
        # 跟随系统（默认）
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # 亮色模式
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
          primary: white
          accent: blue

        # 暗黑模式
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference
          primary: black
          accent: blue
    custom_dir: overrides
    features:
        - navigation.path
        - navigation.tabs
        - navigation.indexes
        - navigation.tabs.sticky
        - navigation.tracking
        - toc.follow
        - content.action.edit
        - content.action.view
        - navigation.footer
        - navigation.path
        - navigation.top

extra_javascript:
    - 'javascripts/analysis.js'
    - 'javascripts/mathjax.js'
    - 'https://unpkg.zhimg.com/mathjax@3/es5/tex-mml-chtml.js'

repo_url: https://github.com/west2-online/fzu-run
repo_name: west2-online/fzu-run
edit_uri: 'edit/main/docs/'
# https://squidfunk.github.io/mkdocs-material/reference/formatting/
markdown_extensions:
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
            generic: true
    - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - footnotes
plugins:
    - git-revision-date-localized
    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
