site_name: 'FZU-RUN'
site_url: https://run.w2fzu.com/
site_author: west2-online
site_description: '福州大学转专业经验手册'
nav:
    - 首页: index.md
    - 关于: about.md
    - 转专业:
        - change-major/README.md
        - 计算机:
            - '[大一]23-机器人工程->计算机类': change-major/cs/231202-1.md
            - '[大一]22-光电信息->计算机类': change-major/cs/230828-1.md
            - '[大一]22-工业设计->大数据': change-major/cs/12.md
            - '[大一]22-土木->软件工程': change-major/cs/11.md
            - '[大二]22-高分子->软件工程': change-major/cs/10.md
            - '[大一]22-土木->计算机类': change-major/cs/230810-2.md
            - '[大一]22-高分子->计算机类': change-major/cs/230810-1.md
            - '[大二]22-地矿->信息安全': change-major/cs/9.md
            - '[大一]21-土木->计算机类': change-major/cs/1.md
            - '[大一]21-环安->计算机类': change-major/cs/6.md
            - '[大二]21-机械->计算机类': change-major/cs/4.md
            - '[大二]21-生工->计算机类': change-major/cs/3.md
            - '[大二]21-生工->软件工程': change-major/cs/2.md
            - '[大一]21-土木->软件工程': change-major/cs/5.md
            - '[大一]21-土木->软件工程': change-major/cs/7.md
            - '[大二]21-材料->软件工程': change-major/cs/8.md
        - 数学:
            - '[大一]21-土木->数学类': change-major/math/1.md
        - 电气:
            - '[大二]22-机械->电气工程及其自动化': change-major/electric/230809.md
            - '[大二]21-土木->电气工程及其自动化': change-major/electric/1.md
            - '[大一]21-环安->电气工程及其自动化': change-major/electric/2.md
            - '[大一]21-化学->电气工程及其自动化': change-major/electric/3.md
        - 物信:
            - '[大二]22-土木->电子科学与技术': change-major/physics/230809.md
            - '[大一]22-土木->电子信息类': change-major/physics/230810-1.md
            - '[大一]22-工业设计->电子信息类': change-major/physics/230810-2.md
            - '[大一]21-外国语->集成电路设计与集成系统': change-major/physics/1.md
            - '[大一]21-化工->集成电路设计与集成系统': change-major/physics/230810-3.md
        - 法学:
            - '[大一]22-英语->法学': change-major/law/230810.md
        - 外国语:
            - '[大一]21-计算机->英语': change-major/foreign/1.md
        - 经管:
            - '[大一]22-外国语->数理金融实验班': change-major/economy/1.md
            - '[大一]21-机械->数理金融实验班':  change-major/economy/2.md
            - '[大一]21-土木->经济学': change-major/economy/3.md
        - 化学:
            - '[大一]22-建筑->嘉锡化学拔尖班':  change-major/chemistry/1.md
        - 备考资源:
            - 通用:
                - 转专业学生名单公示: change-major/source/major-student-list.md
            - 法学:
                - 2022法学转专业笔试题目: change-major/source/2022-law-write-exam.md
                - 2022法学转专业面试名单: change-major/source/2022-law-interview-list.md
                - 2023法学转专业笔试题目: change-major/source/2023-law-write-exam.md
            - 物信:
                - 2022物信转专业笔试题目: change-major/source/2022-physics-write-exam.md
                - 2022物信转专业面试题目: change-major/source/2022-physics-interview-question.md
            - 电气:
                - 电气转专业物理复习资料: change-major/source/electric-review-data.md
            - 数学:
                - 2022数学转专业笔试题目: change-major/source/2022-math-write-exam.md
            - 计算机:
                - 2023计算机机试题目: change-major/source/2023-cs-on-computer-exam.md
                - 2022计算机笔试题目: change-major/source/2022-cs-write-exam.md
                - 2022计算机机试题目: change-major/source/2022-cs-on-computer-exam.md
                - 2021计算机笔试题目: change-major/source/2021-cs-write-exam.md
                - 计算机简答题整理: change-major/source/cs-intro.md
                - 20级计算机学院面试名单: change-major/source/2020-cs-interview-list.md
                - 21级计算机学院面试名单: change-major/source/2021-cs-interview-list.md
    - 研究生:
        - 福州大学:
            - '2023计算机': postgraduate/fzu/1.md
            - "2023-复旦大学工研院": postgraduate/fdu/1.md
theme:
    logo: 'assets/logo.svg'
    name: material
    language: zh
    palette:
        primary: white
        accent: blue
    features:
        - navigation.tabs
        - navigation.indexes
        - navigation.tabs.sticky
        - navigation.tracking
        - toc.follow
        - content.action.edit
        - navigation.footer
        - navigation.path
        - navigation.top

extra_javascript:
    - 'javascripts/analysis.js'

repo_url: https://github.com/west2-online/fzu-run
repo_name: west2-online/fzu-run
edit_uri: 'edit/main/docs/'
